config_setting(
    name = "x86_64-linux",
    define_values = {
        "config": "x86_64-linux",
    },
)

config_setting(
    name = "x86_64-qnx",
    define_values = {
        "config": "x86_64-qnx",
    },
)

config_setting(
    name = "arm64-qnx",
    define_values = {
        "config": "arm64-qnx",
    },
)

config_setting(
    name = "thread_sanitizer_enabled",
    define_values = {"sanitize": "thread"},
)

config_setting(
    name = "address_sanitizer_enabled",
    define_values = {"sanitize": "address"},
)

config_setting(
    name = "ub_sanitizer_enabled",
    define_values = {"sanitize": "undefined"},
)
